### ISSUE TITLE
1,5 more seconds startup time

### ISSUE THREAD

**Issue by ghost** [nmartin84/.doom.d#11]
Hello 
I am using your org-mode setup because I find it awesome, and was wondering if you had 1,5 seconds more at startup.
Are long lines the culprit ? 
Thanks for your time

**Comment by nmartin84** [comment]
Hey there - thanks, not that I have seen but you could try adding `(profiler-start 'cpu+mem)` to test with and without my config to see where its slowing down.

**Comment by ghost** [comment]
it was my mistake
now it starts fast
