### ISSUE TITLE
Sorry to disturb,  I don't know your irc or dicord handle

### ISSUE THREAD

**Issue by ghost** [nmartin84/.doom.d#12]
Hello, I am using your wonderful org config with tecosaur doom config https://github.com/tecosaur/emacs-config

in your config in Publishing section you have 
https://raw.githack.com/nmartin84/raw-files/master/htmlpro.css
is this your proprietary css file ?

thank you for your time, will it possible to describe how we could integrate your config in another?
I guess you must be aware there are people out there "stealing configs" without shame mea culpa
I am building my setup and I prefer to configure EVERYTHING and learn afterward from inside out, meaning, learn first emacs, then org-mode, then lisp, then publishing and writing etc, to do so I need the perfect setup

doom is the best emacs framework but ... missing org setup for writing and publishing 
your config is the best for org-mode and publishing 
and am basing my config on doom config of https://github.com/tecosaur 

Voila I said everything thanks for your time

**Comment by nmartin84** [comment]
Hey there - I'm not real sure what the best path is to merge two configurations other than to test and see what works best for you. You could probably load tecsaur's config, then add my changes to a scratch buffer and evaluate small blocks at a time to test and see what setting fits your needs.

Regarding the CSS file it's mostly from Nicolas P. Rougier's CSS style sheet with some minor tweaks, you can find his original here -> https://www.labri.fr/perso/nrougier/css/main.css
